version: '3.8'

services:
  cockroach:
    image: cockroachdb/cockroach:v24.2.9
    container_name: cockroach-eakt
    hostname: cockroach-eakt
    command: ["start-single-node", "--insecure"]
    ports:
      - "5890:26257"
      - "5880:8080"
    volumes:
      - cockroach-eakt-data:/cockroach/cockroach-eakt-data
    environment:
      - COCKROACH_USER=${COCKROACH_DB_USER}
      - COCKROACH_PASSWORD=${COCKROACH_DB_PASSWORD}
    restart: always

volumes:
  cockroach-eakt-data:
